name: "GoLangCI Linter"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  golangci-lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7 # v7.0.1

      - name: Setup Go
        uses: actions/setup-go@v7 # v7.0.0
        with:
          go-version-file: go.mod

      - name: go mod tidy check
        uses: katexochen/go-tidy-check@v2 # v2.0.1

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9